### ISSUE TITLE
Disable isZoomed on mobile devices

### ISSUE THREAD

**Issue by vs0usa** [taiyomoe/taiyo#1272]
`isZoomed` creates weird effects on mobile. I'd rather have it disabled. We can do this with custom css:

```css
@media(max-width: 768px) {
  img.hover\:scale-125:hover {
    transform: none;
  }
}
```
